### ISSUE TITLE
Pixel Calibrator and Binning

### ISSUE THREAD

**Issue by nanthony21** [nicost/micro-manager#15]
While the pixel calibrator previously accounted for binning settings and adjusted accordingly it seems that it no longer does.

For example, if you have binning at 2x2 and run the pixel calibrator it will save a value which actually corresponds to the size of a 2x2 binned "pixel".

If you then go to the grid creator dialog it will automatically multiply your pixel size by your binning because it assumes that the pixel size is for just a single pixel.

**Comment by nanthony21** [comment]
After taking a closer look it appears that the pixel calibrator has never taken binning into account. However, the issue mentioned above still stands.

**Comment by nicost** [comment]
Fair enough.  Should be easy to add a check for binning (and correct values).

**Comment by nanthony21** [comment]
Fixed in f7842387cc3f48321e287d007d74d05c51dde335
