### ISSUE TITLE
On-the-fly plugin settings are shared between configurations.

### ISSUE THREAD

**Issue by nanthony21** [nicost/micro-manager#19]
The settings for which plugins are in the pipeline, as well as the individual settings for each plugin appear to be shared globally between different configurations. It makes more sense for these settings to be specific to the configuration that they were defined in.

**Comment by nanthony21** [comment]
@nicost . I see where this is being handled. Can I go ahead and change the plugin pipeline from being tied to a profile to being tied to a configuration, or is there a reason to keep it the way it is?

**Comment by nicost** [comment]
I agree that it make more sense for these settings to be specific to a configuration.  It is possible that this code pre-dated the profile system and was never updated.  Would be great if you can create a PR.

**Comment by nanthony21** [comment]
I'll plan on taking a look at it. From what I see so far the configurations use their own format. Would it be safe to add the Pipeline's JSON string to the end of this file or would it need to be formatted to match the rest of the file?

**Comment by nicost** [comment]
Wait.  I misunderstood.  The pipeline settings live completely in Java-space, and should not be in the configuration files that are managed by the (C++) Core.  Adding randomly formatted lines to the configuration file will certainly disrupt loading of that file.  These settings belong in the user profiles (where they currently are, I presume).  It is not a bad idea to tie them to the configuration file used.  I am not sure if there is an api call to get the current configuration file name, but it would be nicest to use that filename as a key in the profile settings.

**Comment by nanthony21** [comment]
Thanks for the clarification. I haven't used the User Profiles so far as I wasn't sure what their purpose is and how they differ from a hardware configuration. So I guess the task is to make it so that a user profile is has a specified default configuration to help keep plugin settings and hardware configuration in sync. It looks like it would also be good to add a way for the user to switch between profiles without restarting the application.

**Comment by nicost** [comment]
Profile switching should never be needed.  Profiles are coupled to the user, not the hardware.  Settings in the profile that depend on the hardware should use keys that reflect the currently loaded configuration.  Getting that is currently not possible though.  I'll ask Mark is he can chime in.

**Comment by nanthony21** [comment]
It seems like the profile system as-is can be used to achieve what I was looking for though it may not be obvious to new users. I'm going to close this.
