### ISSUE TITLE
Photon Transfer Assistant Uses slightly incorrect exposure times.

### ISSUE THREAD

**Issue by nanthony21** [nicost/micro-manager#20]
This is a pretty minor issue but worth reporting. The exposure times recorded by the photon transfer assistant are the exposure times that were attempted to be set, which are not necessarily actual exposure times.

For example, I tested it on a camera that has a minimum exposure time of 30.53 ms. The plugin recorded several measurements below this exposure time but they are inaccurate because even though the plugin was trying to set an exposure time of 1ms the real exposure was bottomed out at 30.

**Comment by nicost** [comment]
Resolved in PR #21
