### ISSUE TITLE
Performing pixel calibration results in a pixel size of 0

### ISSUE THREAD

**Issue by nanthony21** [nicost/micro-manager#22]
Running the pixel calibration with no binning appears to work fine. But running it with binning results in a pixel size of 0. 

I think that this is because at line 403 of f7842387cc3f48321e287d007d74d05c51dde335 we are dividing ints instead of floats.

**Comment by nicost** [comment]
That makes sense.  I just pushed a potential fix (hard to test without actually going to a microscope;)

**Comment by nanthony21** [comment]
This appears to be working

**Comment by nicost** [comment]
Great.  Thanks!
