### ISSUE TITLE
Unknown Error from HamamatsuHam adapter

### ISSUE THREAD

**Issue by nanthony21** [nicost/micro-manager#23]
When starting a sequence acquisition on an OrcaFlash v4 using the HamamatsuHam adapter from a script I will often (but not always) get and `Unknown Error` from the adapter. This can happen in the middle of the sequence or right at the beginning before any images are returned.

I'm not sure if this is a related bug but I have also occasionally gotten the same error when using the `Snap` button. After clicking snap micromanager will freeze up for about a minute before finally returning the error.

Is there any way to debug this issue since the source is closed?

**Comment by nicost** [comment]
Very painful, but you can not get access to the source code of the adapter unless Hamamatsu gives permission.  Best thing is ask Hamamatsu for support (that is how they want it, and there clearly are some issues in their code...).  It would be best to have a reproducible procedure to generate the error. If you have trouble getting through to Hamamatsu, please contact me by email.

**Comment by nanthony21** [comment]
For future reference, at least part of this issue is caused by having a value other than `0` as the intervalMs argument to `startSequenceAcquisition`.

The hamamatsu adapter does not support using this function to set an interval but I didn't think it would matter if I still provided a value anyway. The acquisition will work once, but every time after that it will throw an unknown error.

I have reported this to Hamamatsu.
