### ISSUE TITLE
Photon Transfer Assistant dialog blocks other gui actions.

### ISSUE THREAD

**Issue by nanthony21** [nicost/micro-manager#28]
The dialogs from the PT assistant block other gui buttons from being clicked. E.G. when the dialog tells the user to turn on the light so that it can begin the test, the user cannot click the `open shutter` button or use any other Micromanager related buttons that might be needed to enable illumination. Is there a simple way to make these dialogs non-blocking?

**Comment by nicost** [comment]
Your are right, they should be non-blocking, but I took the easiest route;)  There is no quick way, but certainly doable.  I'll try to have a look this weekend.

**Comment by nicost** [comment]
Changed the code so that the dialogs are now non-blocking.
