### ISSUE TITLE
API Request: Toggle on-the-fly plugin enabled states

### ISSUE THREAD

**Issue by nanthony21** [nicost/micro-manager#29]
It would be good to have a way to toggle the `live mode` and `acquisition mode` enabled states of plugins in the pipeline.

Is this something that could be added to the api for `PipelineFrame` ?

**Comment by nanthony21** [comment]
I have started working on  a fix for this. However it is waiting on a solution for #30.

**Comment by nicost** [comment]
Fixed in PR #31
