### ISSUE TITLE
API Request: Get list of all data processor plugin configurators

### ISSUE THREAD

**Issue by nanthony21** [nicost/micro-manager#30]
Currently the getPipelineConfigurators method of the pipelineFrame only returns the configurators which are enabled. As far as I can tell there is no way to get a list of all configurators regardless of enabled status.

Looking further into the issue I see that the pipeline table model has two methods (`getPipelineConfigurators` and `getEnabledConfigurators`) which both do essentially the same thing, however it doesn't provide any method to return all of the configurators.

**Comment by nicost** [comment]
The Processor API is Mark's (and Chris') design.  To be honest, I have not looked at it much, and will not be in a position to provide good feedback.  I asked @marktsuchida to comment.

**Comment by nanthony21** [comment]
I'd like to be able to write scripts/plugins that toggle the enabled status and settings of processor plugins in the pipeline. However, with the currently available public methods I don't think this can be done in a straightforward way.

In the absence of any feedback from Mark is it OK if I make a few tweaks to the relevant API or should I hold off?

**Comment by nicost** [comment]
Looks like we are done with this one
