### ISSUE TITLE
Build failure at MMStudio

### ISSUE THREAD

**Issue by wsphillips** [nicost/micro-manager#41]
**Update** -- I have solved the missing OME jars during fetchdeps by manually supplying the correct version jars from the maven repo. However, the build still fails with identical errors as shown in "builderror.txt".

Hi,

I am attempting to build MicroManager using the ViewPlusCV branch.

Running OpenSUSE Leap 15.1, two things happen:
Ivy fails to get all dependencies (some OME jars can't be retrieved) and then (if this is ignored) compile errors occur when mmstudio begins...(see copied outputs linked below)

Using Java 1.8 as its the lowest available in the repos right now (If 1.7 is a must I can try to get a reference copy). Tried both gcc 7 and 9. All other dependencies satisfied afaik (i.e. I have successfully built in the past on an older distro).

Suggestions?

[builderror.txt](https://github.com/nicost/micro-manager/files/3166554/builderror.txt)
[ivyerror.txt](https://github.com/nicost/micro-manager/files/3166557/ivyerror.txt)

**Comment by nicost** [comment]
Should be fixed now, see mailing list for detail.  Mailing list is better communication route for build issues.

**Comment by nicost** [comment]
Should be fixed now (for real;).  Run:
make fetchdeps
and then re-run configure.
