### ISSUE TITLE
Image sequences within runnables (worked in 1.4) 

### ISSUE THREAD

**Issue by ctr26** [nicost/micro-manager#62]
Hi all,

I wrote a beanshell script for 1.4 which was able to run a runnable on each frame of a MDA acquisition and within each frame create an image montage of 9 images.

If I attempt to run an image sequence during a runnable I get an error that claims my camera has crashed in MM. Is this a feature change? Is there anyway I can make a similar runnable to the one I wrote before?

Best

Craig

**Comment by ctr26** [comment]
```
import ij.IJ;
import ij.io.FileSaver; 
import org.micromanager.utils.ImageUtils; 
import ij.process.ImageProcessor; 
import ij.ImagePlus; 
import ij.ImageStack;
import ij.plugin.MontageMaker;
import org.micromanager.SequenceSettings;
import org.micromanager.Studio;
import org.micromanager.data.Coords;
import org.micromanager.data.Datastore;
import org.micromanager.data.Image;

acq = mm.acquisitions();
acq.clearRunnables();


runnable = new Runnable() {
		public void run() {
			mmc.stopSequenceAcquisition();
			mmc.snapImage();
	}
};

acq.attachRunnable(-1,-1,-1,-1,runnable);


```

**Comment by nicost** [comment]
I am unsure what this runnable is supposed to accomplish.  All it does is stop the Sequence acquisition of the camera.  Why would a sequence acquisition be running when the runnable is called?  

Some cameras actually crash when you call stopSequenceAcquisition without calling startSequenceAcquisition first (fixed a bug like that in the Andor adapter not too long ago).  

Can you give some context what you are trying to do in the MDA, and what you try to accomplish with this Runnable?

**Comment by ctr26** [comment]
Sorry I tried to make a super cut down version.

For our microscope we require 9 images per frame to be captured and then stored as an image montage (3x3). This runnable is it's full form (in 1.4) at each frame runs a capture sequence for the 9, stores and saves them to disk and does so for each hence why the runnable is attached at (-1,-1,-1,-1)

**Comment by nicost** [comment]
It would be really useful if you can make a version of your script that reproduces the problem with the demo configuration.  Without that, I would have to go through the trouble of trying to exactly recreate your issue myself, something that I am not likely to have the time for..

**Comment by ctr26** [comment]
The script as of 1.4 was this: Ideally it would've used addImageToAcquisition() to add the image as the current image, but, in 1.4 there wasn't anyway of knowing what coordinate you were at beyond counting yourself to use addImageToAcquisition().
```
// SIM MODE
// Author: Craig Russell, craig.russell@npl.co.uk
// MAKE SURE AUTO SHUTTER IS DISABLED

import ij.IJ;
import ij.io.FileSaver; 
import org.micromanager.utils.ImageUtils; 
import ij.process.ImageProcessor; 
import ij.ImagePlus; 
import ij.ImageStack;
import ij.plugin.MontageMaker;
import org.micromanager.SequenceSettings;

acq.clearRunnables();

static String intToString(int num, int digits) {
    StringBuffer s = new StringBuffer(digits);
    int zeroes = digits - (int) (Math.log(num) / Math.log(10)) - 1; 
    for (int i = 0; i < zeroes; i++) {
        s.append(0);
    }
    return s.append(num).toString();
}

runnable = new Runnable() {

  public void run() {

      root_directory = gui.getAcquisitionPath()+"\\";
	   print(root_directory);
	   folder_created = new File(root_directory).mkdirs();
	   print(folder_created);
      ++count;

      ImageStack stack = new ImageStack(512,512);
      prefix = gui.getAcquisitionSettings().prefix;
      directory = gui.getAcquisitionPath();
      file = gui.getAcquisitionNames();
      filename = directory + "\\" + "" + intToString(count,5) + ".tiff";
      print(filename);

      ImageProcessor proc0 = ImageUtils.makeProcessor(mmc); 	
		mmc.startSequenceAcquisition(9,0,false);
	
		while (mmc.isSequenceRunning() || mmc.getRemainingImageCount() > 0){
			if (mmc.getRemainingImageCount() > 0) {
				img = mmc.popNextImage();
				proc0 = ImageUtils.makeProcessor(mmc, img); 	
				stack.addSlice(proc0);
			}
		}

      ImagePlus imagestack = new ImagePlus("Stack",stack); 
      MontageMaker montager = new MontageMaker();
      FileSaver fss =  new FileSaver(imagestack);
      montage = montager.makeMontage2(imagestack,3,3,1.00,1,9,1,0,false);
		FileSaver fsss =  new FileSaver(montage);
		fsss.saveAsTiff(filename);
		//addImageToAcquisition("",-1,-1,-1,-1,aa);		
   }
};

acq.attachRunnable(-1,-1,-1,-1,runnable);
```

**Comment by ctr26** [comment]
The 2.0-gamma script would be something like this, where I take the 3 by 3 montage image and putImage() that into the MDA datastore or just a random side datastore. But, the issue is the runnable fails on   mmc.startSequenceAcquisition(9,0,false); whereas in 1.4 it did not. The error is claims is an error in the camera so my assumption is the camera has already been told it is about to receive x images. 

`import ij.IJ;
import ij.io.FileSaver; 
import org.micromanager.utils.ImageUtils; 
import ij.process.ImageProcessor; 
import ij.ImagePlus; 
import ij.ImageStack;
import ij.plugin.MontageMaker;
import org.micromanager.SequenceSettings;
import org.micromanager.Studio;
import org.micromanager.data.Coords;
import org.micromanager.data.Datastore;
import org.micromanager.data.Image;

//mmc=mm.CMMCore();
store = mm.data().createRAMDatastore();

acq = mm.acquisitions();
acq.clearRunnables();


runnable = new Runnable() {
		public void run() {
    ImageStack stack = new ImageStack(512,512);
    ImageProcessor proc0 = ImageUtils.makeProcessor(mmc); 	
    mmc.startSequenceAcquisition(9,0,false);
    while (mmc.isSequenceRunning() || mmc.getRemainingImageCount() > 0){
      if (mmc.getRemainingImageCount() > 0) {
        img = mmc.popNextImage();
        proc0 = ImageUtils.makeProcessor(mmc, img); 	
        stack.addSlice(proc0);
        }
      }
    ImagePlus imagestack = new ImagePlus("Stack",stack); 
    MontageMaker montager = new MontageMaker();
    montage = montager.makeMontage2(imagestack,3,3,1.00,1,9,1,0,false);
    store.putImage(montage)
	}
};

acq.attachRunnable(-1,-1,-1,-1,runnable);
`

**Comment by nicost** [comment]
There are a bunch of errors when running that script.  I always find it easiest to troubleshoot Beanshell scripts by running MM in an IDE (I use Netbeans) and looking at the errors and stackTraces to see what is happening.  There are a couple of impossible conversion of images in your script.  Fixing most of these leads to the following script that works with the demo camera.  Test this first with the demo configuration (and you can try to push the montage into a MM datastore, certainly possible...), and once that works, check if there are issues when running it with your hardware.


```
import ij.IJ;
import ij.io.FileSaver;
import org.micromanager.utils.ImageUtils;
import ij.process.ImageProcessor;
import ij.ImagePlus;
import ij.ImageStack;
import ij.plugin.MontageMaker;
import org.micromanager.SequenceSettings;
import org.micromanager.Studio;
import org.micromanager.data.Coords;
import org.micromanager.data.Datastore;
import org.micromanager.data.Image;
import org.micromanager.internal.utils.imageanalysis.ImageUtils;

//mmc=mm.CMMCore();
store = mm.data().createRAMDatastore();

acq = mm.acquisitions();
acq.clearRunnables();

runnable = new Runnable() {
	public void run() {
		ImageStack stack = new ImageStack(512,512);
		mmc.startSequenceAcquisition(9,0,false);
		while (mmc.isSequenceRunning() || mmc.getRemainingImageCount() > 0) {
			if (mmc.getRemainingImageCount() > 0) {
				tImg = mmc.popNextTaggedImage();
				proc0 = ImageUtils.makeProcessor(tImg);
				stack.addSlice(proc0);
			}
		}
		ImagePlus imagestack = new ImagePlus("Stack",stack);
		MontageMaker montager = new MontageMaker();
		montage = montager.makeMontage2(imagestack,3,3,1.00,1,9,1,0,false);
		montage.show();
		//store.putImage(montage);
	}
};

acq.attachRunnable(-1,-1,-1,-1,runnable);
```

**Comment by ctr26** [comment]
Apologies, I should've left my thanks here. I didn't realise you could run micromanager in netbeans to get errors, that's very useful!

**Comment by ctr26** [comment]
@nicost I can send my SIM montaging script to you as an example script if you'd like?

**Comment by nicost** [comment]
@ctr26 Funny, I got an email saying that your added this comment to this thread, but I don't see it here: 

> I can send my SIM montaging script to you as an example script if you'd like?

In any case, simply post your script here.  I can add it to the scripts in the mm2.0-gamma scripts directory (always useful to have examples there).

**Comment by ctr26** [comment]
https://github.com/ctr26/MMSIMPlugin

Hi @nicost 

I've made two plugins that are useful for SIM, neither is finished by both are usable.
https://github.com/ctr26/MMLiveFFTPlugin <- This adds a live FFT window as a GearPlugin
https://github.com/ctr26/MMSIMPlugin <- This makes a runnable take n images per MDA acquire (and might work with snap, unsure) and gets the Coords using Events.

Do you have any comments or how they could be improved? Could they be integrated into the this repository? What do I need to do to they to make that happen?

Best

Craig

**Comment by nicost** [comment]
@ctr26 : Sorry for the long delay.  I just had a look at your MMLiveFFT plugin, but was confused about getting it to work.  It only seems to work when Live mode is running when you start the plugin, otherwise no image ever shows up in it.  

Also, it makes more sense to me to insert this in the plugin menu rather then under the Gearbutton, since it only works on live display, and not on every viewer.  Maybe this makes more sense as an On-The-Fly-Processor (although it would likely not really process the real image, but calculate an FFT and show in a separate window more or less as a side effect.

Let me know if you want me to look into in more detail!   Also, maybe good to open as a new issue.

**Comment by ctr26** [comment]
> @ctr26 : Sorry for the long delay. I just had a look at your MMLiveFFT plugin, but was confused about getting it to work. It only seems to work when Live mode is running when you start the plugin, otherwise no image ever shows up in it.
> 
> Also, it makes more sense to me to insert this in the plugin menu rather then under the Gearbutton, since it only works on live display, and not on every viewer. Maybe this makes more sense as an On-The-Fly-Processor (although it would likely not really process the real image, but calculate an FFT and show in a separate window more or less as a side effect.
> 
> Let me know if you want me to look into in more detail! Also, maybe good to open as a new issue.

I've put the LiveFFT discussion here:
https://github.com/nicost/micro-manager/issues/81
