### ISSUE TITLE
Runnable MDA coords lags behind acquisition

### ISSUE THREAD

**Issue by ctr26** [nicost/micro-manager#64]
Hi again,

I would like get the coords of the current image being captured in a runnable, but it appears that the runnable script runs before the image is acquire that populates the Datastore for the current acquisition. Is there anyway of getting round this to force the MDA acquisition to fire and populate it's datastore while my runnable script is running?

```
import ij.IJ;
import ij.io.FileSaver;
import org.micromanager.utils.ImageUtils;
import org.micromanager.SequenceSettings;
import org.micromanager.Studio;
import org.micromanager.data.Coords;
import org.micromanager.data.Datastore;
import org.micromanager.data.Image;


acq = mm.acquisitions();
acq.clearRunnables();


runnable = new Runnable() {
	public void run() {
		try{
		images = mm.live().snap(false);
		store_mda = mm.displays().getCurrentWindow().getDatastore();
		coords_mda = store_mda.getMaxIndices();
		print(coords_mda);
		}
		catch(Exception e){
			print(e);
		}
	}
};

acq.attachRunnable(-1,-1,-1,-1,runnable);
```

output:

```
bsh % java.lang.NullPointerException: Attempt to invoke method getDatastore on null value
<time=0 position=0 z=0 channel=0>
<position=0 z=0 channel=0 time=1>
```

Should be:
```

<time=0 position=0 z=0 channel=0>
<position=0 z=0 channel=0 time=1>
<position=0 z=0 channel=0 time=2>
```

**Comment by nicost** [comment]
I wouldn't say "Should be", but rather "I'd like it to be".  

This does not work the way you would like it to work.  The Displaywindow is only created once the first image is inserted in the Datastore, so there is no DisplayWindow when you call mm.displays().getCurrentWindow().  The only (semi-) reliable way that I am aware of that you can use to know which image will be acquired (the runnable always runs before the image is acquired, not after), is to get the acquisition settings, analyze them, and use you knowledge of when the runnable will be called to back calculate which image will be acquired.  

Quite ugly, I agree, but that is how things were designed...

**Comment by ctr26** [comment]
Can beanshell scripts hook the NewImageEvent event of a datastore? I'd be very grateful of an example script, I've trie myself to no avail.

`import org.micromanager.events.AcquisitionStartedEvent;

events.registerForEvents(AcquisitionStartedEvent);

public void test(AcquisitionStartedEvent){
	print('a');
}`

**Comment by nicost** [comment]
Beanshell is a relatively old Java scripting language and I doubt that it works with these more recent Java annotations.  It seems that you are much better off writing an MM plugin (in and IDE) so that you get access to all the niceties available, plus have a much easier time debugging.

It is always interesting to see where that cutoff point between a script and a plugin is, but it looks to me that you are past that point;)

**Comment by ctr26** [comment]
Hi nicost,

I just have a quick question about micromanager versions. Am I correct in thinking that the latest nightly build is gamma and I should be using this javadoc?

https://valelab4.ucsf.edu/~MM/doc-2.0.0-gamma/mmstudio/

If so what is micromanager-2.0.1-snapshot, is this not the latest that I should be using on maven.

I ask because get errors trying to create a display from a datastore and it looks like in gamma displaying a datastore requires a dataprovider object to be made instead but the wiki doesn't mention this. Funnily enough though the beanshell example of creating a display directly from a datastore does work. 

The error is that there is no method for displays ().createDisplay(Datastore store).

Best

Craig

**Comment by nicost** [comment]
> Am I correct in thinking that the latest nightly build is gamma and I should be using this javadoc?
> 
> https://valelab4.ucsf.edu/~MM/doc-2.0.0-gamma/mmstudio/

Yes.  It is created every night during the build, so should exactly match the source code in the ViewerPlusCV branch.

> If so what is micromanager-2.0.1-snapshot, is this not the latest that I should be using on maven.

I don't know what micromanager-2.0.1-snapshot is.  What link are you following?  Micro-Manager has not put builds on maven, so if this is really on maven, someone else may have put something somewhere.  You are on your own with that version.

**Comment by ctr26** [comment]
I lifted the maven file from your MMClearVolume plugin and some arbitrary
2.0.1 libraries do download, though they appear to be 2.0.0 alpha.

Best

Craig

**Comment by nicost** [comment]
> I lifted the maven file from your MMClearVolume plugin and some arbitrary 2.0.1 libraries do download, though they appear to be 2.0.0 alpha.

Note that the last commit in that repository was from 2017.  I updated the README there to warn others against using that code now.

**Comment by ctr26** [comment]
The way I'm currently getting the effect I want is using these events

_AcquisitionStartedEvent_
to get the dataprovider

_DataProviderHasNewImageEvent_
to acquire my 9 images

_AcquisitionEndedEvent_
to save

I'll put the code online when It's very functional

**Comment by ctr26** [comment]
https://valelab4.ucsf.edu/~nstuurman/maven/org/micromanager/

I found where your maven files are kept for future reference @nicost
