### ISSUE TITLE
attachRunnable in micromanager gamma - something changed?

### ISSUE THREAD

**Issue by nicost** [nicost/micro-manager#68]
Reported by MonikaP:

I have a script that worked in micromanager beta. It contains the following
lines:

mm.acquisitions().attachRunnable(0, 0, 0, 0, starting); // f, p, c, s 
mm.acquisitions().attachRunnable(0, -1, 0, 0, runnable); // f, p, c, s 
mm.acquisitions().runAcquisition();

In micromanager gamma, weirdness happends. If any one of the two runnables
is commented out, the rest works. If both gets attached, the first runnable
"starting" gets executed, the second "runnable" gets executed twice (when
there are three positions on the list, so should execute 3 times), but no
images are received, "Received 00 of 18 images" in Acquisition Progress. The
runnables are only for opening external shutters and waiting between
positions.

Any idea what can be going wrong? Or how I can rewrite my code?

Okay, I did some testing with a very simple runnable: 

stupid1 = new Runnable() {
	public void run() {
		 print("I'm stupid runnable 1");
	}
};

It is not possible to attach two runnables to the same plane. Combinations
such as:

mm.acquisitions().attachRunnable(0, 0, 0, 0, stupid1); 
mm.acquisitions().attachRunnable(0, 0, 0, 0, stupid2); //two runnables to
position 0

mm.acquisitions().attachRunnable(0, 0, 0, 0, stupid1); 
mm.acquisitions().attachRunnable(0, -1, 0, 0, stupid2); //one for position
0, one for all positions

Cause images to stop coming (but the runnables are still run, the messages
get printed!).

Why is this so? How can I achieve what I need, run one piece of code at
startup, and another one (ie waiting) for every position?

**Comment by ctr26** [comment]
You could attach the new runnable inside the initialisation runnable? Will check at my workstation.

```
mm.acquisitions().clearRunnables();


public stupid2 = new Runnable() {
public void run() {
print("I'm stupid runnable 2");
}
};

stupid1 = new Runnable() {
public void run() {
print("I'm stupid runnable 1");
mm.acquisitions().attachRunnable(-1, -1, -1, -1, stupid2);
}
};

mm.acquisitions().attachRunnable(0, 0, 0, 0, stupid1);
```

**Comment by pawlowska** [comment]
@nicost yes, it works for me now, thanks!
