### ISSUE TITLE
Question: Is there anyway of adding Plugin Parameters as Device properties?

### ISSUE THREAD

**Issue by ctr26** [nicost/micro-manager#69]
Is there anyway of including the internel properties of a plugin the the list of Device Properties?
I can see a lot of practical use for being able to change what a plugin is doing during a MDA and adding common plugin settings to the device window. I can't however find any instance of the properties of a plugin being visible and usable by a plugin though.

What would be really great is if there were some interface like DevicePlugin whereby a java plugin could impersonate a device and update it self with some applySettings() method, vaguely simliar to the autofocus.

If this does already exist please excuse me.

Best

Craig

**Comment by nanthony21** [comment]
As far as I'm aware nothing like this currently exists, though I can see how it would be useful.

Your idea is a good idea but I think that it would likely be a lot of work to implement.

Probably an easier thing to do would be to just create something like the device property window for your specific plugin.

Don't take my word for it though, I've never tried something like this.
