### ISSUE TITLE
problems opening dataset from mm2beta in mm2gamma

### ISSUE THREAD

**Issue by pawlowska** [nicost/micro-manager#76]
I have datasets of, eg, 12x3GB stacks acquired with mm2beta. With mm2beta, I can open them using "Open (virtual)" within seconds, or I get a warning about RAM if trying to Open normally, also within seconds.
Trying to open the same datasets in mm2gamma results in empty progress bar which is not moving, I also don't see anything in particular happening in the system monitor, no error message... My student reports that the dataset finally opens after an hour or so, I wasn't that patient.
What can be causing this?

**Comment by nicost** [comment]
Please generate a problem report (Help > Report a problem).
