### ISSUE TITLE
Debug fails in NetBeans 11

### ISSUE THREAD

**Issue by nanthony21** [nicost/micro-manager#77]
Not sure if this should be considered a micromanager error or a netbeans error.

When trying to debug MMStudio in Apache NetBeans 11.0 Micro-Manager crashes with a null pointer exception at https://github.com/nicost/micro-manager/blob/420ed35254d5b8e30188fdb49dd5cf50e11ca99a/mmstudio/src/main/java/org/micromanager/internal/MainFrame.java#L380

The cause of this can be traced further back to the fact that while the classloader does find many scijava and imagej plugins, it does not find any of the `quickaccess` plugins: https://github.com/nicost/micro-manager/blob/420ed35254d5b8e30188fdb49dd5cf50e11ca99a/mmstudio/src/main/java/org/micromanager/internal/pluginmanagement/DefaultPluginManager.java#L127

When using the exact same project settings in Netbeans 9.0 everything works fine. I'm not sure what causes this discrepancy.

**Comment by nicost** [comment]
I think that I run into the same problem on occasion in Netbeans 8.2. I don't understand enough of the Scijava stuff and class path/loader issues to trouble shoot this.

**Comment by nicost** [comment]
Just tested with Netbeans 11 myself, and to my great surprise, MM build, compiled, and ran fine even using Java 11 (rel. 5 from AdoptOpenJDK).  Good sign!  Dealbreaker for me was that the "code injection" green button never became active, but that seems to be more of a Netbeans bug.
