### ISSUE TITLE
CMake for vcs2019

### ISSUE THREAD

**Issue by triccyx** [nicost/micro-manager#98]
Hi!
I have created a version of MM that is working with vcs2019 and CMake project.
The projects I have modified are MMCore and MMDevice. All the other dll module don't need modification to be loaded.
Principal modifications:
- MMCore and MMDevice, std:: instead boost:: equivalent, minor warnings fix
- c++17
- CMake instead vsc solution for now only for Windows (for Linux It will be easier).

Do you think we can integrate this version somehow in the project?
Perhaps is it possible to create a repo only for core functionalities without modules?

**Comment by nicost** [comment]
Thanks @triccyx !  

Development of micro-manager has returned to the micro-manager/micro-manager repository, so it is better to move this issue there.  Your first two points sound very good.  We will never move to CMake (based on experience), so if your are planning a PR, it will be good to split your CMake code out.  

Very much agree with the need to move MMCore and MMDevice into their own repositories (which is in the planning stage, but we are focussing on 2.0 release right now).

**Comment by triccyx** [comment]
Move to
https://github.com/micro-manager/micro-manager/issues/774
